---
- name: Installing php-fpm and deps
  apt: name={{ item }} state=present
  with_items:
    - php7.0
    - php7.0-common
    - php7.0-opcache
    - php7.0-opcache
    - php7.0-fpm
    - php7.0-mcrypt
    - php7.0-xml
    - php7.0-mysql
    - php7.0-gd
    - php7.0-mbstring

#- name: Deploying www.conf
#  template: src=www.conf dest=/etc/php/7.0/fpm/pool.d/www.conf owner=root
#  notify: restart php-fpm
