---
- import_tasks: create_user_key.yml
- import_tasks: python.yml
- import_tasks: git.yml
- import_tasks: zsh.yml
- import_tasks: wget.yml
- import_tasks: htop.yml
- import_tasks: vim.yml
- import_tasks: user.yml
- import_tasks: zip.yml
- import_tasks: npm.yml
- import_tasks: curl.yml
